name: smart_trolley
description: "UMMI Trolley - Smart Shopping Application"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  ai_barcode_scanner: ^7.1.0
  http: ^1.2.0
  webview_flutter: ^4.7.0

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3

  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1   

flutter_icons:                      
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/onboarding.png
    - assets/icon/icon.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins.ttf
          weight: 400
        - asset: assets/fonts/poppins_medium.ttf
          weight: 500
        - asset: assets/fonts/poppins_bold.ttf
          weight: 700
        - asset: assets/fonts/poppins_black.ttf
          weight: 900